### PR TITLE
fix(cimpl): update Message.headers arg-type

### PR DESCRIPTION
**Pull request by rudo-ro**
This pull request includes changes to the `confluent_kafka-stubs/cimpl.pyi` file to update the type annotations for the `headers` and `set_headers` methods in the `Message` class. The most important changes are:

* [`confluent_kafka-stubs/cimpl.pyi`](diffhunk://#diff-70277a322388ba6571f8c669ce92378eb34c18fe3d47a4ab703a7cfc9f84ea7fL310-R316): Updated the `headers` method to return a list of tuples with `str` and `bytes` types instead of `str` and `str | bytes` types.
* [`confluent_kafka-stubs/cimpl.pyi`](diffhunk://#diff-70277a322388ba6571f8c669ce92378eb34c18fe3d47a4ab703a7cfc9f84ea7fL310-R316): Updated the `set_headers` method to accept a list of tuples with `str` and `bytes` types instead of `str` and `str | bytes` types.

edited by @benbenbang

### CODE REVIEW

**Comment by rudo-ro** [comment]
@benbenbang opened a new pr with new branch to meet label specification.

1. looks like the labeler is broken, I also cannot manually add labels
```
Run actions/labeler@v5
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Warning: The action requires write permission to add labels to pull requests. For more information please refer to the action documentation: https://github.com/actions/labeler#permissions
Error: Resource not accessible by integration
```

2. looks like `ruff-format` is broken. running locally out the box on latest version passed in root dir for me. should i be running these checks against the dockerfile? if so some instructions on how to do so would be great!
```
ruff check .
All checks passed!
```
(from the check)
```
ruff-format..............................................................Failed
- hook id: ruff-format
- files were modified by this hook

1 file reformatted
```

**Comment by benbenbang** [comment]
labeler seems need some extra setup, however I believe I already granted to fork. Let me try something

**Comment by benbenbang** [comment]
please fix the tests, I will handle the labler part. Thanks

**Comment by benbenbang** [comment]
labler fixed :)

**Comment by KowalskiThomas** [comment]
👋  Hello! Is there a way we can go forward with this? If anything needs help, I can definitely give a hand!

Otherwise, I have this other PR in draft which has the perk of also fixing `set_headers` https://github.com/benbenbang/types-confluent-kafka/pull/212

**Comment by benbenbang** [comment]
I'll take over :)

**Comment by benbenbang** [comment]
Hello @rudo-ro 

Since you didn't reply, I fixed the title (you have a white space in the prefix)
I'll merge this PR

**Comment by rudo-ro** [comment]
thanks @benbenbang !

**Pull request merged**
