### PR TITLE
docs: contribution guide and issue template

### LINKED ISSUE #199: Some minor issues with the contributing guide issue template
### Initial Checks

- [X] I confirm that I'm using Types-Confluent-Kafka

### Description

I tried to follow the contribution guide without poetry but I assume it was deprecated.

### Example Code

_No response_

### Python, verion of Types-confluent-kafka. verion of Confluent-kafka-python, your applications settings & OS Version

```Text
https://github.com/benbenbang/types-confluent-kafka/blob/main/.github/CONTRIBUTING.md
```

### Affected Components

- [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`)
- [ ] Apache Kafka broker version
- [ ] Client configuration: `{...}` is provided
- [ ] Operating system is provided
- [ ] Provide IDE screenshot if it's possible

### PR DESCRIPTION
**Pull request by mj0nez**
⚠️ Noted that the latest version of Confluent Kafka Python is `2.3.x` now.

- For introducing new signatures, please use `feat`
- For fixing compatible signature in `2.2.x`, please use `fix`

### **Description:**

Updated guide for contributors w/o poetry and fixed a minor issue with the bug-issue template.

### **Related Issue:**

Closes #199 

### **Type of change**:

Please delete options that are not relevant.

- [x ] Documentation (Updating or adding documentation, docstrings, etc.)

### **Additional Details:**

Any additional context, explanation, or reasoning for the changes made.

### **Screenshots:**

If applicable, provide screenshots or images to visually represent the changes.

### **Checklist:**

- [x] All code follows the project's coding style and conventions.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings or errors.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding updates to the documentation.

### CODE REVIEW

**Comment by benbenbang** [comment]
do you mind if I push to your branch?

**Comment by mj0nez** [comment]
Not at all, please.

**Comment by benbenbang** [comment]
btw `confluent_kafka` == `confluent-kafka`

so I think this is fine

**Comment by benbenbang** [comment]
all good ✅ 
thanks again

**Pull request merged**
