### PR TITLE
fix: rename parameter in Consumer.list_topics

### PR DESCRIPTION
**Pull request by KowalskiThomas**
### **Description:**

This PR updates the stubs for `Consumer.list_topics` to have a `topic` parameter and not a `topics` one. This is the actual definition as can be seen upstream here: https://github.com/confluentinc/confluent-kafka-python/blob/0e5706b71adbfea5a178f1bec3587ec29bb8aff9/src/confluent_kafka/src/Metadata.c#L416-L427

### **Related Issue:**

(none)

### **Type of change**:

Bug fix (non-breaking change which fixes an issue)

### **Additional Details:**

Type checks in my code are currently failing due to this incorrect definition in the stubs. The code works in practice with the singular `topic` parameter, and doesn't with the plural `topics` parameter.

### **Screenshots:**

(none)

### **Checklist:**

- [x] All code follows the project's coding style and conventions.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings or errors.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding updates to the documentation.

### CODE REVIEW

**Comment by benbenbang** [comment]
Hey @KowalskiThomas 

Thanks for the contribution!
Mind if helping to include the labels of the compatible version?
thanks

**Comment by KowalskiThomas** [comment]
Thanks for your reply! 

Based on the history, this has been around for quite some time (see [here](https://github.com/confluentinc/confluent-kafka-python/blob/32ad9f6ddf74fad4da6f6ad35447293d557d4cae/src/confluent_kafka/src/Metadata.c#L415-L426) which was for version 1.5.2). 

I'm sorry but I'm not sure though how to include the labels of compatible versions 🤔  I can't seem to edit the PR labels on the side if that's what you're talking about (sorry, it's my first time doing this)

**Comment by benbenbang** [comment]
Hello @KowalskiThomas 

Basically all the signature should align with the c file in the source

here's our [reference](https://github.com/confluentinc/confluent-kafka-python/blob/0e5706b71adbfea5a178f1bec3587ec29bb8aff9/src/confluent_kafka/src/Consumer.c#L1503)

**Comment by KowalskiThomas** [comment]
Thanks for your reply. 

I'm not sure I follow how that is a breaking change and not a bug.  
The functionality in `types-confluent-kafka` (i.e. the type hint) is already broken as far as I can tell (because it differs from the C code, and has pretty much always differed).

**Comment by benbenbang** [comment]
sorry I misread your `s` all good more me

**Pull request merged**
