### PR TITLE
fix: update Message.headers() arg-type

### PR DESCRIPTION
**Pull request by rudo-ro**
⚠️ Noted that the latest version of Confluent Kafka Python is `2.3.x` now.

- For introducing new signatures, please use `feat`
- For fixing compatible signature in `2.2.x`, please use `fix`

### **Description:**

`Message.headers()` has wrong type set, as does other supporting method Message.set_headers()

### **Related Issue:**

https://github.com/benbenbang/types-confluent-kafka/issues/206

### **Type of change**:

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### **Additional Details:**

Any additional context, explanation, or reasoning for the changes made.

### **Screenshots:**

If applicable, provide screenshots or images to visually represent the changes.

### **Checklist:**

- [ ] All code follows the project's coding style and conventions.
- [ ] I have performed a self-review of my own code.
- [ ] My changes generate no new warnings or errors.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding updates to the documentation.

### CODE REVIEW

**Comment by rudo-ro** [comment]
hi @benbenbang am I reading the docs and code correctly here?

**Comment by benbenbang** [comment]
hello @rudo-ro,

Sorry for the very late reply. 

Could you please confirm the confluent-kafka-python version and add related labels

Thank you

**Comment by rudo-ro** [comment]
```Text
confluent-kafka==2.3.0
types-confluent-kafka==1.2.2
```

### Description

https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Message.headers

in the docs I'm seeing

```
headers()

    Retrieve the headers set on a message. Each header is a key valuepair. Please note that header keys are ordered and can repeat.

    Returns

        list of two-tuples, one (key, value) pair for each header.
    Return type

        [(str, bytes),…] or None.

```

[In the code I'm seeing](https://github.com/benbenbang/types-confluent-kafka/blob/26ee5216094731a652ef444bb0362c47f9393118/confluent_kafka-stubs/cimpl.pyi#L301-L309);

```
    def headers(self) -> list[tuple[str, str | bytes]] | None: ...
```

### Example Code

_No response_

### Python, verion of Types-confluent-kafka. verion of Confluent-kafka-python, your applications settings & OS Version

**Comment by benbenbang** [comment]
Can you please rebase and fix the errors?

Also, please help confirm the compatible version and add the version labels on the sidebar. it will facilitate the release

**Comment by benbenbang** [comment]
I think this one is dup

**Pull request closed without merging**
